### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by lokerhp**
Heya,

This PR fixes a typo and removes a space!
Well thats everything, so not a lot to review :)

### CODE REVIEW

**Review by burbuli8ra — APPROVED** [review]

**Comment by andrewm4894** [comment]
@netdata/cloud-fe a power user in our community asked about this fix for a (embarrassing :) ) typo. 

Is it as easy a fix as it looks? If so any reason not to merge it?

**Comment by andrewm4894** [comment]
thanks @lokerhp !!!!

**Review by AlexNti — APPROVED** [review]

**Review by libekonst — APPROVED** [review]
Thanks for that @lokerhp

**Review by jjtsou — APPROVED** [review]

**Comment by burbuli8ra** [comment]
I think it's good to go!
Merging it and thanks a lot for the contribution @lokerhp !

**Pull request merged**
