### PR TITLE
Fix links to documentation and text for database engine in new dashboard menu

### PR DESCRIPTION
**Pull request by joelhans**
The same fixes as found in netdata/#9394, but for the new dashboard.

### CODE REVIEW

**Comment by joelhans** [comment]
@jacekkolasa GitHub told me to update the branch, so I clicked the button and it seemed to just rebase. Hopefully that still works!

**Comment by jacekkolasa** [comment]
@joelhans the "update" button still works fine :) Dashboard repo doesn't need re-approval so you can merge.

**Comment by joelhans** [comment]
@jacekkolasa I don't have write access, so you'll have to merge!

**Comment by jacekkolasa** [comment]
@joelhans you should have access now

**Pull request merged**
