### PR TITLE
Reduce spacing of menu items in right bar

### PR DESCRIPTION
**Pull request by christophidesp**
**Before**

Screenshot 2022-04-01 at 16 44 53

**After**
Screenshot 2022-04-01 at 16 40 43

Fixes: https://github.com/netdata/cloud-frontend/issues/3049

cc: @burbuli8ra @novykh I haven't reviewed the changes on the Agent, if you can please review them.

### CODE REVIEW

**Review by burbuli8ra — COMMENTED** [review]
@christophidesp I see that your changes are working ok on `cloud-frontend` repo, but as we synced offline, I am not able to see the view to have been updated on `agent` as well!
So, since you need to open `dashboard` to apply the changes there as well to have the two views synchronised with the changes, either we need to sync offline in order to help you open `dashboard` locally and work on it or I will need to apply the changes on the repo, when I finish with the task I am currently working on! 😄 

Also (kind reminder for myself as well), please note that @novykh has done an npm release, so before we do another release on this one this one, we need to make sure that we will not overwrite his changes!

**Comment by novykh** [comment]
Yes please hold this PR until further notice. Thank you

**Comment by burbuli8ra** [comment]
@christophidesp from me its ok, but since I have made a commit myself as well, if @netdata/cloud-fe could also check the code as well and approve it so we can merge it!

**Comment by christophidesp** [comment]
Thanks @burbuli8ra for taking care of this!

**Review by jjtsou — APPROVED** [review]

**Pull request merged**
