### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by rex4539** [comment]
@novykh Could you please review?

**Review by novykh — APPROVED** [review]
Thanks!

**Review by novykh — APPROVED** [review]

**Review by jjtsou — APPROVED** [review]

**Comment by rex4539** [comment]
Rebased

**Comment by rex4539** [comment]
Rebased again.

**Comment by rex4539** [comment]
One more rebase.

**Comment by rex4539** [comment]
One more.

**Comment by jacekkolasa** [comment]
Thanks @rex4539 !

**Pull request merged**
